use super::*;
use calamine::{Data, Reader, Xlsx};
use std::io::{Cursor, Read};

// ---- harness -----------------------------------------------------------

fn export_app(
    parent: Build,
    owner_id: OwnerId,
    linked_builds: Vec<Build>,
    inventory: support::inventory::SeededInventoryRepository,
) -> (
    axum::Router,
    Arc<support::inventory::SeededInventoryRepository>,
) {
    let inventory = Arc::new(inventory);
    let router = build_router(
        AppState::new(Arc::new(configured_workspace_owned_by(
            "Industry", owner_id,
        )))
        .with_industry_repository(Arc::new(FixtureIndustryRepository {
            build: Some(parent),
            linked_builds: std::sync::Mutex::new(linked_builds),
            ..Default::default()
        }))
        .with_sde_repository(Arc::new(FixtureSdeRepository))
        .with_inventory_repository(inventory.clone())
        .with_production_repository(Arc::new(FixtureProductionRepository {
            type_id: 0,
            available_to_this_build: 0,
            average_historical_unit_cost: None,
        })),
    );
    (router, inventory)
}

/// [`export_app`], but with fixed market prices wired (mirrors
/// `build_cost_projection::cost_app`) -- so a Buy boundary's fresh cost
/// is complete instead of always incomplete. No facility/ESI wiring
/// (matches `export_app`/`cost_app`): installation stays incomplete.
fn export_app_priced(
    parent: Build,
    owner_id: OwnerId,
    linked_builds: Vec<Build>,
    inventory: support::inventory::SeededInventoryRepository,
) -> (
    axum::Router,
    Arc<support::inventory::SeededInventoryRepository>,
) {
    let inventory = Arc::new(inventory);
    let router = build_router(
        AppState::new(Arc::new(configured_workspace_owned_by(
            "Industry", owner_id,
        )))
        .with_industry_repository(Arc::new(FixtureIndustryRepository {
            build: Some(parent),
            linked_builds: std::sync::Mutex::new(linked_builds),
            market_items: [
                price_item(34, "Tritanium", "5"),
                price_item(35, "Pyerite", "11"),
                price_item(90_001, "Rifter Hull Section", "800"),
                price_item(5_876, "Rifter", "5000000"),
            ]
            .into_iter()
            .map(|item| (item.type_id, item))
            .collect(),
            ..Default::default()
        }))
        .with_sde_repository(Arc::new(FixtureSdeRepository))
        .with_inventory_repository(inventory.clone())
        .with_production_repository(Arc::new(FixtureProductionRepository {
            type_id: 0,
            available_to_this_build: 0,
            average_historical_unit_cost: None,
        })),
    );
    (router, inventory)
}

fn seeded(balances: Vec<(i64, u64)>) -> support::inventory::SeededInventoryRepository {
    support::inventory::SeededInventoryRepository::new(balances)
}

async fn post_export(
    app: axum::Router,
    build_id: BuildId,
    body: serde_json::Value,
) -> (StatusCode, axum::http::HeaderMap, Vec<u8>) {
    let response = app
        .oneshot(
            Request::builder()
                .method("POST")
                .uri(format!("/api/builds/{}/export-verification", build_id.0))
                .header("content-type", "application/json")
                .body(Body::from(body.to_string()))
                .unwrap(),
        )
        .await
        .unwrap();
    let status = response.status();
    let headers = response.headers().clone();
    let bytes = to_bytes(response.into_body(), usize::MAX)
        .await
        .unwrap()
        .to_vec();
    (status, headers, bytes)
}

fn open(bytes: &[u8]) -> Xlsx<Cursor<Vec<u8>>> {
    calamine::open_workbook_from_rs(Cursor::new(bytes.to_vec()))
        .expect("generated bytes parse as a valid .xlsx workbook")
}

fn sheet_names(wb: &Xlsx<Cursor<Vec<u8>>>) -> Vec<String> {
    wb.sheet_names().iter().map(|s| s.to_string()).collect()
}

fn cell_text(data: &Data) -> String {
    match data {
        Data::String(s) => s.clone(),
        Data::Float(f) => f.to_string(),
        Data::Int(i) => i.to_string(),
        Data::Bool(b) => b.to_string(),
        _ => String::new(),
    }
}
fn cell_f64(data: &Data) -> Option<f64> {
    match data {
        Data::Float(f) => Some(*f),
        Data::Int(i) => Some(*i as f64),
        Data::String(s) => s.parse().ok(),
        Data::Bool(b) => Some(if *b { 1.0 } else { 0.0 }),
        _ => None,
    }
}

/// header -> value map for the first data row whose `key_header` == `key`.
fn table_row(
    wb: &mut Xlsx<Cursor<Vec<u8>>>,
    sheet: &str,
    key_header: &str,
    key: &str,
) -> std::collections::HashMap<String, Data> {
    let range = wb
        .worksheet_range(sheet)
        .unwrap_or_else(|_| panic!("sheet {sheet} exists"));
    let headers: Vec<String> = range
        .rows()
        .next()
        .expect("header row")
        .iter()
        .map(cell_text)
        .collect();
    let key_col = headers
        .iter()
        .position(|h| h == key_header)
        .unwrap_or_else(|| panic!("column {key_header} on sheet {sheet}"));
    for row in range.rows().skip(1) {
        if row.get(key_col).map(cell_text).as_deref() == Some(key) {
            return headers.iter().cloned().zip(row.iter().cloned()).collect();
        }
    }
    panic!("no row on {sheet} with {key_header} == {key}");
}

/// Like `table_row`, but for an operation sheet whose material table
/// header sits at 0-based row 18 (below the key/value header block).
fn op_table_row(
    wb: &mut Xlsx<Cursor<Vec<u8>>>,
    sheet: &str,
    type_id: &str,
) -> std::collections::HashMap<String, Data> {
    let range = wb.worksheet_range(sheet).unwrap();
    let rows: Vec<&[Data]> = range.rows().collect();
    let headers: Vec<String> = rows[18].iter().map(cell_text).collect();
    for row in &rows[19..] {
        if row.first().map(cell_text).as_deref() == Some(type_id) {
            return headers.iter().cloned().zip(row.iter().cloned()).collect();
        }
    }
    panic!("no material row on {sheet} for type {type_id}");
}

fn headers_of(wb: &mut Xlsx<Cursor<Vec<u8>>>, sheet: &str) -> Vec<String> {
    wb.worksheet_range(sheet)
        .unwrap()
        .rows()
        .next()
        .unwrap()
        .iter()
        .map(cell_text)
        .collect()
}

/// Sheet display-name -> its `xl/worksheets/sheetN.xml`, resolved through
/// `xl/workbook.xml` + its rels. (calamine's `worksheet_formula` is
/// unreliable for our workbooks, so formula assertions read the XML.)
fn sheet_xml_map(bytes: &[u8]) -> std::collections::HashMap<String, String> {
    let mut archive = zip::ZipArchive::new(Cursor::new(bytes.to_vec())).unwrap();
    let read = |archive: &mut zip::ZipArchive<Cursor<Vec<u8>>>, name: &str| -> String {
        let mut f = archive.by_name(name).unwrap();
        let mut s = String::new();
        f.read_to_string(&mut s).unwrap();
        s
    };
    let workbook_xml = read(&mut archive, "xl/workbook.xml");
    let rels_xml = read(&mut archive, "xl/_rels/workbook.xml.rels");
    // rId -> target file
    let mut rid_target: std::collections::HashMap<String, String> =
        std::collections::HashMap::new();
    for chunk in rels_xml.split("<Relationship ").skip(1) {
        let id = attr(chunk, "Id");
        let target = attr(chunk, "Target");
        if let (Some(id), Some(target)) = (id, target) {
            rid_target.insert(id, target.trim_start_matches('/').to_string());
        }
    }
    let mut out = std::collections::HashMap::new();
    for chunk in workbook_xml.split("<sheet ").skip(1) {
        let name = attr(chunk, "name");
        let rid = chunk
            .split("r:id=\"")
            .nth(1)
            .and_then(|s| s.split('"').next())
            .map(str::to_string);
        if let (Some(name), Some(rid)) = (name, rid) {
            if let Some(target) = rid_target.get(&rid) {
                let path = if target.starts_with("xl/") {
                    target.clone()
                } else {
                    format!("xl/{target}")
                };
                let xml = read(&mut archive, &path);
                out.insert(name, unescape_xml(&xml));
            }
        }
    }
    out
}

fn attr(chunk: &str, key: &str) -> Option<String> {
    chunk
        .split(&format!("{key}=\""))
        .nth(1)
        .and_then(|s| s.split('"').next())
        .map(str::to_string)
}

fn unescape_xml(s: &str) -> String {
    s.replace("&gt;", ">")
        .replace("&lt;", "<")
        .replace("&quot;", "\"")
        .replace("&apos;", "'")
        .replace("&amp;", "&")
}

/// All `<f>...</f>` formula bodies on `sheet`, unescaped, joined by `\n`.
fn sheet_formulas(bytes: &[u8], sheet: &str) -> String {
    let xml = sheet_xml_map(bytes).remove(sheet).unwrap_or_default();
    xml.split("<f>")
        .skip(1)
        .filter_map(|s| s.split("</f>").next())
        .collect::<Vec<_>>()
        .join("\n")
}

/// The formula body of the cell at Excel `col_letter``row1` on `sheet`,
/// or "" if that cell is not a formula.
fn formula_cell(bytes: &[u8], sheet: &str, cell_ref: &str) -> String {
    let xml = sheet_xml_map(bytes).remove(sheet).unwrap_or_default();
    let needle = format!("<c r=\"{cell_ref}\"");
    let Some(rest) = xml.split(&needle).nth(1) else {
        return String::new();
    };
    let Some(cell) = rest.split("</c>").next() else {
        return String::new();
    };
    cell.split("<f>")
        .nth(1)
        .and_then(|s| s.split("</f>").next())
        .unwrap_or("")
        .to_string()
}

/// Row index of the first Operations row whose `Op #` == `op_index`, then
/// the value of `header` on that row.
fn ops_value(wb: &mut Xlsx<Cursor<Vec<u8>>>, op_index: u32, header: &str) -> Data {
    table_row(wb, "Operations", "Op #", &op_index.to_string())
        .remove(header)
        .unwrap()
}

fn all_worksheet_xml(bytes: &[u8]) -> String {
    let mut archive = zip::ZipArchive::new(Cursor::new(bytes.to_vec())).unwrap();
    let mut out = String::new();
    for i in 0..archive.len() {
        let mut file = archive.by_index(i).unwrap();
        if file.name().starts_with("xl/worksheets/sheet") {
            let mut buf = String::new();
            file.read_to_string(&mut buf).unwrap();
            out.push_str(&buf);
        }
    }
    out
}

fn sheet1_xml(bytes: &[u8]) -> String {
    let mut archive = zip::ZipArchive::new(Cursor::new(bytes.to_vec())).unwrap();
    let mut file = archive.by_name("xl/worksheets/sheet1.xml").unwrap();
    let mut buf = String::new();
    file.read_to_string(&mut buf).unwrap();
    buf
}

/// The op sheet names, in workbook order (between "Materials" and
/// "Allocation Ledger").
fn op_sheet_names(wb: &Xlsx<Cursor<Vec<u8>>>) -> Vec<String> {
    let names = sheet_names(wb);
    let start = names.iter().position(|n| n == "Materials").unwrap() + 1;
    let end = names.iter().position(|n| n == "Allocation Ledger").unwrap();
    names[start..end].to_vec()
}

// A reaction-child fixture: Rifter (mfg) root whose Hull Section (90_001)
// component is Build-resolved to reaction formula 90_003 (50 Pyerite ->
// 1 Hull), Pyerite bought.
fn reaction_child_chain(runs: u64) -> (Build, Vec<Build>, BuildId, OwnerId) {
    let (parent, ws, owner_id) = rifter_root(runs);
    let parent = super::with_saved_resolution(
        parent,
        90_001,
        iskworks_core::RecipeSelection::Reaction {
            reaction_formula_type_id: 90_003,
        },
    );
    let parent_id = parent.id;
    let now = chrono::Utc::now();
    let reaction_hull = fixture_link(
        Build {
            id: BuildId::new(),
            workspace_id: ws,
            owner_id,
            name: "Hull Section reaction".to_string(),
            recipe: iskworks_core::BuildRecipe::Reaction(iskworks_core::CapturedReactionFormula {
                source_sde_dataset_id: uuid::Uuid::new_v4(),
                source_sde_version: "test".to_string(),
                reaction_formula_type_id: 90_003,
                reaction_formula_name: "Rifter Hull Section Reaction Formula".to_string(),
                duration_seconds_per_run: Some(50),
                materials: vec![iskworks_core::CapturedRecipeLine {
                    type_id: 35,
                    type_name: "Pyerite".to_string(),
                    quantity_per_run: 50,
                    sort_order: 0,
                }],
                products: vec![iskworks_core::CapturedRecipeLine {
                    type_id: 90_001,
                    type_name: "Rifter Hull Section".to_string(),
                    quantity_per_run: 1,
                    sort_order: 0,
                }],
                fingerprint: "recipe".to_string(),
            }),
            runs: 2 * runs,
            notes: String::new(),
            revision: 1,
            created_at: now,
            updated_at: now,
            draft_planning: Some(iskworks_core::DraftPlanningSnapshot {
                input: iskworks_core::DraftPlanningInput {
                    material_scope: iskworks_core::DEFAULT_MARKET_SCOPE,
                    output_scope: iskworks_core::DEFAULT_MARKET_SCOPE,
                    manual_price_list_id: None,
                    expected_manual_price_list_revision: None,
                    material_pricing_policy: iskworks_core::MarketPricingPolicy::HighestBuy,
                    output_pricing_policy: iskworks_core::MarketPricingPolicy::LowestSell,
                    pricing_selections: Vec::new(),
                    blueprint_selection: None,
                    manufacturing_facility: None,
                    reaction_facility: None,
                    facility_eiv_manual: false,
                    component_resolutions: Vec::new(),
                    fulfillment_scopes: Vec::new(),
                },
                updated_at: now,
            }),
            recipe_currency: iskworks_core::RecipeCurrency::Current,
            active_sde_version: Some("test".to_string()),
            product_category_name: None,
            product_group_name: None,
            selected_blueprint_origin: None,
            has_owned_blueprint: false,
        },
        parent_id,
        90_001,
    );
    (parent, vec![reaction_hull], parent_id, owner_id)
}

fn hull_section_reacted() -> serde_json::Value {
    serde_json::json!([
        {"typeId": 90_001, "recipe": {"mode": "reaction", "reactionFormulaTypeId": 90_003}}
    ])
}

// ---- tests -----------------------------------------------------------

// -- A -- exact sheet order.
#[tokio::test]
async fn export_sheet_order() {
    let (parent, linked, parent_id, owner_id) = nested_chain(1);
    let (app, _inv) = export_app(
        parent,
        owner_id,
        linked,
        seeded(vec![(90_001, 1), (34, 400)]),
    );
    let (status, _h, bytes) = post_export(app, parent_id, overlay(1, hull_section_built())).await;
    assert_eq!(status, StatusCode::OK);
    let wb = open(&bytes);
    let names = sheet_names(&wb);
    assert_eq!(names[0], "Summary");
    assert_eq!(names[1], "Types");
    assert_eq!(names[2], "Blueprints");
    assert_eq!(names[3], "Operations");
    assert_eq!(names[4], "Materials");
    assert_eq!(names[names.len() - 2], "Allocation Ledger");
    assert_eq!(names[names.len() - 1], "Engineering - Requirements");
    // Rifter -> Hull -> Pyerite = 3 operations between Materials and Ledger.
    assert_eq!(op_sheet_names(&wb).len(), 3, "one sheet per walked node");
}

// -- B / C -- Types: one row per distinct referenced type_id, metadata
// from `type_reference`.
#[tokio::test]
async fn export_types_sheet_is_the_type_dictionary() {
    let (parent, linked, parent_id, owner_id) = nested_chain(1);
    let (app, _inv) = export_app(parent, owner_id, linked, seeded(vec![(90_001, 1)]));
    let (status, _h, bytes) = post_export(app, parent_id, overlay(1, hull_section_built())).await;
    assert_eq!(status, StatusCode::OK);
    let mut wb = open(&bytes);

    let range = wb.worksheet_range("Types").unwrap();
    let ids: Vec<i64> = range
        .rows()
        .skip(1)
        .filter_map(|row| cell_f64(&row[0]).map(|f| f as i64))
        .collect();
    let mut sorted = ids.clone();
    sorted.sort_unstable();
    sorted.dedup();
    assert_eq!(
        ids, sorted,
        "Types rows are distinct + ascending by type_id"
    );
    // Referenced everywhere: materials 34 / 35 / 90_001, blueprint types
    // 6_830 / 90_002 / 91_002.
    for id in [34, 35, 90_001, 6_830, 90_002, 91_002] {
        assert!(ids.contains(&id), "Types has a row for {id}");
    }
    // (C) name / group / category / volume come from `type_reference`.
    let trit = table_row(&mut wb, "Types", "Type ID", "34");
    assert_eq!(cell_text(&trit["Type Name"]), "Tritanium");
    assert_eq!(cell_text(&trit["Group Name"]), "Mineral");
    assert_eq!(cell_text(&trit["Category Name"]), "Material");
    assert_eq!(cell_f64(&trit["Packaged Volume (m³)"]), Some(0.01));
}

// -- D -- non-Types sheets derive item names via INDEX/MATCH (no XLOOKUP).
#[tokio::test]
async fn export_name_lookups_use_index_match() {
    let (parent, linked, parent_id, owner_id) = nested_chain(1);
    let (app, _inv) = export_app(parent, owner_id, linked, seeded(vec![(90_001, 1)]));
    let (status, _h, bytes) = post_export(app, parent_id, overlay(1, hull_section_built())).await;
    assert_eq!(status, StatusCode::OK);
    let materials_f = sheet_formulas(&bytes, "Materials");
    assert!(
        materials_f.contains("INDEX(Types_Name,MATCH("),
        "Materials Item is INDEX/MATCH against Types_Name: {materials_f}"
    );
    assert!(!materials_f.contains("XLOOKUP"), "no XLOOKUP anywhere");
    let ops_f = sheet_formulas(&bytes, "Operations");
    assert!(ops_f.contains("INDEX(Types_Name,MATCH("));
    assert!(!all_worksheet_xml(&bytes).contains("XLOOKUP"));
}

// -- E / F -- Blueprints dedups by blueprint/formula type; Operations has
// one row per node.
#[tokio::test]
async fn export_blueprints_dedup_and_operations_per_node() {
    let (parent, linked, parent_id, owner_id) = nested_chain(1);
    let (app, _inv) = export_app(parent, owner_id, linked, seeded(vec![(90_001, 1)]));
    let (status, _h, bytes) = post_export(app, parent_id, overlay(1, hull_section_built())).await;
    assert_eq!(status, StatusCode::OK);
    let mut wb = open(&bytes);

    let bp_ids: Vec<String> = wb
        .worksheet_range("Blueprints")
        .unwrap()
        .rows()
        .skip(1)
        .filter_map(|row| cell_f64(&row[0]).map(|f| (f as i64).to_string()))
        .collect();
    let mut unique = bp_ids.clone();
    unique.sort();
    unique.dedup();
    assert_eq!(bp_ids.len(), unique.len(), "one Blueprints row per type");
    // Rifter bp 6_830, Hull bp 90_002, Pyerite bp 91_002.
    assert_eq!(bp_ids.len(), 3);

    let op_count = wb.worksheet_range("Operations").unwrap().rows().count() - 1;
    assert_eq!(op_count, 3, "one Operations row per walked node");
    // Every blueprint an operation references is in Blueprints exactly once.
    for op_index in 0..3u32 {
        let bp = cell_text(&ops_value(&mut wb, op_index, "Blueprint/Formula Type ID"));
        assert!(
            bp_ids.contains(&bp),
            "operation {op_index} bp {bp} in Blueprints"
        );
    }
}

// -- Blueprints is STATIC recipe reference only: no per-operation state
// (ME / TE / Runs / Facility). Two operations that share a blueprint may
// carry different ME on Operations without Blueprints implying otherwise.
#[tokio::test]
async fn export_blueprints_is_static_reference_only() {
    let (parent, linked, parent_id, owner_id) = nested_chain(1);
    let (app, _inv) = export_app(parent, owner_id, linked, seeded(vec![(90_001, 1)]));
    let (status, _h, bytes) = post_export(app, parent_id, overlay(1, hull_section_built())).await;
    assert_eq!(status, StatusCode::OK);
    let mut wb = open(&bytes);

    let bp_headers = headers_of(&mut wb, "Blueprints");
    for forbidden in ["ME", "TE", "Runs", "Facility", "Facility ID"] {
        assert!(
            !bp_headers.iter().any(|h| h == forbidden),
            "Blueprints must not carry per-operation column {forbidden}: {bp_headers:?}"
        );
    }
    for required in [
        "Blueprint/Formula Type ID",
        "Activity",
        "Product Type ID",
        "Output per Run",
        "Base Material Count",
    ] {
        assert!(
            bp_headers.iter().any(|h| h == required),
            "Blueprints keeps static column {required}: {bp_headers:?}"
        );
    }
    // ME lives per-operation only -- Operations + the OP sheets.
    let ops_headers = headers_of(&mut wb, "Operations");
    assert!(ops_headers.iter().any(|h| h == "ME"));
    assert!(ops_headers.iter().any(|h| h == "TE"));
}

// -- Operations carries the relational key (Blueprint/Formula Type ID)
// *and* the display name; Total Output multiplies the right two columns.
#[tokio::test]
async fn export_operations_blueprint_key_and_total_output_formula() {
    let (parent, linked, parent_id, owner_id) = nested_chain(1);
    let (app, _inv) = export_app(parent, owner_id, linked, seeded(vec![(90_001, 1)]));
    let (status, _h, bytes) = post_export(app, parent_id, overlay(1, hull_section_built())).await;
    assert_eq!(status, StatusCode::OK);
    let mut wb = open(&bytes);
    let headers = headers_of(&mut wb, "Operations");

    let id_col = headers
        .iter()
        .position(|h| h == "Blueprint/Formula Type ID");
    let name_col = headers.iter().position(|h| h == "Blueprint/Formula");
    assert!(id_col.is_some(), "Operations has Blueprint/Formula Type ID");
    assert!(name_col.is_some(), "Operations has Blueprint/Formula");
    // Root operation's blueprint id is the Rifter blueprint (6_830).
    assert_eq!(
        cell_text(&ops_value(&mut wb, 0, "Blueprint/Formula Type ID")),
        "6830"
    );

    // Total Output (Excel) == Runs (Excel) * Output per Run, by whichever
    // columns those headers actually land in.
    let col = |name: &str| -> String {
        let idx = headers.iter().position(|h| h == name).unwrap();
        let mut s = String::new();
        let mut n = idx as u32;
        loop {
            s.insert(0, (b'A' + (n % 26) as u8) as char);
            if n < 26 {
                break;
            }
            n = n / 26 - 1;
        }
        s
    };
    let runs_c = col("Runs (Excel)");
    let out_c = col("Output per Run");
    let total_c = col("Total Output (Excel)");
    // row 2 = first data row.
    assert_eq!(
        formula_cell(&bytes, "Operations", &format!("{total_c}2")),
        format!("${runs_c}2*${out_c}2"),
        "Total Output = Runs (Excel) * Output per Run"
    );
}

// -- OP sheet Check flags a mismatch on ANY of the six quantity diffs, and
// cross-checks the ledger's independent recipe recompute.
#[tokio::test]
async fn export_op_check_covers_all_six_quantity_diffs() {
    let (parent, linked, parent_id, owner_id) = nested_chain(1);
    let (app, _inv) = export_app(
        parent,
        owner_id,
        linked,
        seeded(vec![(90_001, 1), (34, 400)]),
    );
    let (status, _h, bytes) = post_export(app, parent_id, overlay(1, hull_section_built())).await;
    assert_eq!(status, StatusCode::OK);
    let root_sheet = op_sheet_names(&open(&bytes))[0].clone();
    let check = formula_cell(&bytes, &root_sheet, "AG20");
    // Required / Planned Use / Shortage / Child Runs / Produced / Surplus
    // diff columns are K / R / U / Y / AB / AE on an operation sheet.
    for diff in ["$K20=0", "$R20=0", "$U20=0", "$Y20=0", "$AB20=0", "$AE20=0"] {
        assert!(check.contains(diff), "OP Check misses {diff}: {check}");
    }
    assert!(
        check.contains("$I20='Allocation Ledger'!$T$2"),
        "OP Check cross-checks the ledger recompute: {check}"
    );
}

// -- G -- operation sheet names: valid, <=31, unique, stable, hash suffix.
#[tokio::test]
async fn export_operation_sheet_names_are_valid_and_stable() {
    let (parent, linked, parent_id, owner_id) = nested_chain(1);
    let (app, _inv) = export_app(parent, owner_id, linked, seeded(vec![(90_001, 1)]));
    let (_s, _h, first) =
        post_export(app.clone(), parent_id, overlay(1, hull_section_built())).await;
    let (_s, _h, second) =
        post_export(app.clone(), parent_id, overlay(1, hull_section_built())).await;

    let ops_a = op_sheet_names(&open(&first));
    let ops_b = op_sheet_names(&open(&second));
    assert_eq!(ops_a, ops_b, "sheet names stable across re-exports");
    let mut lower: Vec<String> = ops_a.iter().map(|n| n.to_lowercase()).collect();
    lower.sort();
    lower.dedup();
    assert_eq!(lower.len(), ops_a.len(), "case-insensitively unique");
    for name in &ops_a {
        assert!(name.chars().count() <= 31, "{name:?} <= 31 chars");
        assert!(
            !name.contains(['[', ']', ':', '*', '?', '/', '\\']),
            "{name:?} has no invalid sheet char"
        );
        assert!(
            name.ends_with(')') && name.contains('('),
            "{name:?} carries a (hash) suffix"
        );
    }
}

// -- I -- Operations root Runs (Excel) is the editor-overlay run count.
#[tokio::test]
async fn export_root_runs_excel_is_overlay_runs() {
    // persisted runs 5, overlay 1.
    let (parent, linked, parent_id, owner_id) = nested_chain(5);
    let (app, _inv) = export_app(parent, owner_id, linked, seeded(vec![(90_001, 1)]));
    let (status, _h, bytes) = post_export(app, parent_id, overlay(1, hull_section_built())).await;
    assert_eq!(status, StatusCode::OK);
    let mut wb = open(&bytes);
    assert_eq!(cell_f64(&ops_value(&mut wb, 0, "Runs (Excel)")), Some(1.0));
    assert_eq!(
        cell_f64(&ops_value(&mut wb, 0, "Runs (ISKWorks)")),
        Some(1.0)
    );
}

// -- J -- child operation Runs references the parent operation's Excel
// Child Runs via a per-op defined name.
#[tokio::test]
async fn export_child_runs_reference_parent_operation() {
    let (parent, linked, parent_id, owner_id) = nested_chain(1);
    let (app, _inv) = export_app(
        parent,
        owner_id,
        linked,
        seeded(vec![(90_001, 1), (34, 400)]),
    );
    let (status, _h, bytes) = post_export(app, parent_id, overlay(1, hull_section_built())).await;
    assert_eq!(status, StatusCode::OK);
    let wb0 = open(&bytes);
    let op_names = op_sheet_names(&wb0);

    // Operations: child rows carry `=OpRuns_<i>`, root is literal.
    assert_eq!(formula_cell(&bytes, "Operations", "K2"), ""); // op 0 (root): literal
    assert_eq!(formula_cell(&bytes, "Operations", "K3"), "OpRuns_1"); // op 1: Hull
    assert_eq!(formula_cell(&bytes, "Operations", "K4"), "OpRuns_2"); // op 2: Pyerite

    // The child OP sheet's header Runs cell (B6, row 5 / col 1) = the name.
    let hull_sheet = &op_names[1];
    assert_eq!(formula_cell(&bytes, hull_sheet, "B6"), "OpRuns_1");

    // The defined name resolves to the parent sheet's Excel-Child-Runs
    // column (W); never to an API column.
    let names_xml = {
        let mut a = zip::ZipArchive::new(Cursor::new(bytes.clone())).unwrap();
        let mut f = a.by_name("xl/workbook.xml").unwrap();
        let mut s = String::new();
        f.read_to_string(&mut s).unwrap();
        s
    };
    assert!(
        names_xml.contains("OpRuns_1"),
        "OpRuns_1 defined name present"
    );
    assert!(
        names_xml.contains(&format!("'{}'!$W$", op_names[0])),
        "OpRuns_1 points at the parent (Rifter) sheet's column W: {names_xml}"
    );
}

// -- K / L / M -- OP recipe Excel Required is self-computed (not from
// API Required), and cross-checks the ledger's independent recompute;
// allocation cells are direct references into this boundary's ledger row.
#[tokio::test]
async fn export_operation_sheet_recipe_and_allocation_formulas() {
    let (parent, linked, parent_id, owner_id) = nested_chain(1);
    let (app, _inv) = export_app(
        parent,
        owner_id,
        linked,
        seeded(vec![(90_001, 1), (34, 400)]),
    );
    let (status, _h, bytes) = post_export(app, parent_id, overlay(1, hull_section_built())).await;
    assert_eq!(status, StatusCode::OK);
    let wb0 = open(&bytes);
    let root_sheet = op_sheet_names(&wb0)[0].clone();
    let f = sheet_formulas(&bytes, &root_sheet);

    // (K) Excel Required references base ($E) / runs ($F) / me ($G) /
    // facility ($H); never the ISKWorks Required column ($J).
    assert!(
        f.contains("ROUNDUP(ROUND($E20*$F20*$G20*$H20,6),0)"),
        "OP Excel Required chains from primitives: {f}"
    );
    assert!(
        !f.contains("$J20*") && !f.contains("*$J20"),
        "Excel Required never uses API Required"
    );
    // (M) allocation cells are direct single-cell references into this
    // boundary's Allocation Ledger row (row 2 for traversal 0). A
    // whole-column INDEX would form a circular reference now that the
    // ledger's Excel Required points back at this sheet.
    assert!(
        f.contains("'Allocation Ledger'!$P$2"),
        "Starting Inventory: {f}"
    );
    assert!(f.contains("'Allocation Ledger'!$X$2"), "Prior Allocation");
    assert!(f.contains("'Allocation Ledger'!$Y$2"), "Available");
    assert!(f.contains("'Allocation Ledger'!$Z$2"), "Excel Planned Use");
    assert!(f.contains("'Allocation Ledger'!$AC$2"), "Excel Shortage");
    assert!(!f.contains("INDEX(Ledger_"), "no whole-column ledger INDEX");
    // (L) Check cross-checks the ledger's independent recipe recompute
    // (col T), not its allocator Excel Required (which is this cell).
    assert!(
        f.contains("$I20='Allocation Ledger'!$T$2"),
        "Check vs ledger recompute: {f}"
    );
    // Child runs chain from EXCEL shortage, not API.
    assert!(f.contains("ROUNDUP($S21/$V21,0)"));
}

// -- An edit to an OP-sheet primitive propagates
// through the ledger allocation into every descendant. Trace the whole
// Excel dependency chain by formula, and assert no API column appears.
#[tokio::test]
async fn export_op_primitive_edit_propagates_through_ledger_to_descendants() {
    let (parent, linked, parent_id, owner_id) = nested_chain(1);
    let (app, _inv) = export_app(
        parent,
        owner_id,
        linked,
        seeded(vec![(90_001, 1), (34, 400)]),
    );
    let (status, _h, bytes) = post_export(app, parent_id, overlay(1, hull_section_built())).await;
    assert_eq!(status, StatusCode::OK);
    let wb0 = open(&bytes);
    let names = op_sheet_names(&wb0);
    let (root_sheet, hull_sheet) = (names[0].clone(), names[1].clone());

    // (A) parent OP Excel Required (I21, the 90_001 Build boundary) is a
    // pure function of that sheet's primitive cells.
    assert_eq!(
        formula_cell(&bytes, &root_sheet, "I21"),
        "MAX($F21,ROUNDUP(ROUND($E21*$F21*$G21*$H21,6),0))"
    );
    // (B) the ledger's allocator Excel Required (col S) for that boundary
    // (ledger row 3) is a direct reference back to that OP cell -- not a
    // recompute, not the API value.
    assert_eq!(
        formula_cell(&bytes, "Allocation Ledger", "S3"),
        format!("'{root_sheet}'!$I$21")
    );
    // (C) ledger Planned Use (col Z) is driven by ledger Excel Required.
    assert_eq!(
        formula_cell(&bytes, "Allocation Ledger", "Z3"),
        "IF($K3=\"Full\",0,MIN($S3,$Y3))"
    );
    // (D) ledger Shortage (col AC) = ledger Excel Required - Planned Use.
    assert_eq!(
        formula_cell(&bytes, "Allocation Ledger", "AC3"),
        "MAX($S3-$Z3,0)"
    );
    // (E) parent OP Excel Shortage (S21) reads that ledger Shortage cell.
    assert_eq!(
        formula_cell(&bytes, &root_sheet, "S21"),
        "'Allocation Ledger'!$AC$3"
    );
    // (F) parent OP Excel Child Runs (W21) = ROUNDUP(OP Shortage / out).
    assert_eq!(
        formula_cell(&bytes, &root_sheet, "W21"),
        "IF(AND(OR($C21=\"build\",$C21=\"reaction\"),$S21>0,$V21>0),ROUNDUP($S21/$V21,0),0)"
    );
    // (G) child OP Runs (B6) = the OpRuns_1 name = parent W21.
    assert_eq!(formula_cell(&bytes, &hull_sheet, "B6"), "OpRuns_1");
    let workbook_xml = {
        let mut a = zip::ZipArchive::new(Cursor::new(bytes.clone())).unwrap();
        let mut s = String::new();
        a.by_name("xl/workbook.xml")
            .unwrap()
            .read_to_string(&mut s)
            .unwrap();
        unescape_xml(&s)
    };
    assert!(
        workbook_xml.contains(&format!("'{root_sheet}'!$W$21")),
        "OpRuns_1 resolves to the parent Excel Child Runs cell: {workbook_xml}"
    );
    // (H) child OP recipe rows use that child Runs cell.
    assert_eq!(formula_cell(&bytes, &hull_sheet, "F20"), "$B$6");
    assert!(formula_cell(&bytes, &hull_sheet, "I20").contains("$F20"));

    // No API column may appear anywhere in that Excel-side chain. On the
    // ledger the API columns are U / AA / AD / AG (Required / Planned Use
    // / Shortage / Child Runs); on an operation sheet they are J / Q / T /
    // X (the "ISKWorks *" columns).
    let ledger_api = ["$U", "$AA", "$AD", "$AG"];
    let op_api = ["$J", "$Q", "$T", "$X"];
    for (sheet, cell, forbidden) in [
        (root_sheet.as_str(), "I21", &op_api),
        (root_sheet.as_str(), "S21", &op_api),
        (root_sheet.as_str(), "W21", &op_api),
        ("Allocation Ledger", "S3", &ledger_api),
        ("Allocation Ledger", "Z3", &ledger_api),
        ("Allocation Ledger", "AC3", &ledger_api),
    ] {
        let body = formula_cell(&bytes, sheet, cell);
        for col in forbidden {
            assert!(
                !body.contains(col),
                "{sheet}!{cell} = {body:?} must not reference API column {col}"
            );
        }
    }
}

// -- N -- no array / CSE formula anywhere.
#[tokio::test]
async fn export_uses_no_array_formulas() {
    let (parent, linked, parent_id, owner_id) = nested_chain(1);
    let (app, _inv) = export_app(
        parent,
        owner_id,
        linked,
        seeded(vec![(90_001, 1), (34, 400)]),
    );
    let (status, _h, bytes) = post_export(app, parent_id, overlay(1, hull_section_built())).await;
    assert_eq!(status, StatusCode::OK);
    let xml = all_worksheet_xml(&bytes);
    assert!(!xml.contains("t=\"array\""), "no <f t=\"array\"> cells");
    assert!(!xml.contains("SUMPRODUCT"), "no SUMPRODUCT");
}

// -- O -- Full scope still consumes zero inventory (ledger formula).
#[tokio::test]
async fn export_full_scope_consumes_zero() {
    let (parent, _ws, owner_id) = rifter_root(1);
    let parent_id = parent.id;
    let (app, _inv) = export_app(parent, owner_id, Vec::new(), seeded(vec![(34, 1_000)]));
    let body = serde_json::json!({
        "recipe": {"mode": "manufacturing", "blueprintTypeId": 6_830},
        "runs": 1,
        "pricingSelections": [],
        "componentResolutions": [],
        "fulfillmentScopes": [{"typeId": 34, "scope": "full"}],
    });
    let (status, _h, bytes) = post_export(app, parent_id, body).await;
    assert_eq!(status, StatusCode::OK);
    let mut wb = open(&bytes);
    let trit = table_row(&mut wb, "Allocation Ledger", "Type ID", "34");
    assert_eq!(cell_text(&trit["Scope"]), "Full");
    assert_eq!(cell_f64(&trit["API Planned Use"]), Some(0.0));
    assert!(
        sheet_formulas(&bytes, "Allocation Ledger").contains("=\"Full\",0,MIN("),
        "ledger Excel Planned Use zeroes Full scope"
    );
}

// -- P -- a fully-covered Build intermediate creates no child OP sheet.
#[tokio::test]
async fn export_covered_build_intermediate_no_child_sheet() {
    let (parent, linked, parent_id, owner_id) = nested_chain(1);
    let (app, _inv) = export_app(parent, owner_id, linked, seeded(vec![(90_001, 2)]));
    let (status, _h, bytes) = post_export(app, parent_id, overlay(1, hull_section_built())).await;
    assert_eq!(status, StatusCode::OK);
    let wb0 = open(&bytes);
    assert_eq!(op_sheet_names(&wb0).len(), 1, "only the Rifter operation");
    let root_sheet = op_sheet_names(&wb0)[0].clone();
    let mut wb = open(&bytes);
    let hull = op_table_row(&mut wb, &root_sheet, "90001");
    assert_eq!(
        cell_text(&hull["Child Operation"]),
        "Covered - not expanded"
    );
}

// -- Q -- a partially-covered Build intermediate creates a child OP sheet
// and a hyperlink from the parent row.
#[tokio::test]
async fn export_partial_build_intermediate_creates_child_sheet() {
    let (parent, linked, parent_id, owner_id) = nested_chain(1);
    let (app, _inv) = export_app(parent, owner_id, linked, seeded(vec![(90_001, 1)]));
    let (status, _h, bytes) = post_export(app, parent_id, overlay(1, hull_section_built())).await;
    assert_eq!(status, StatusCode::OK);
    let wb0 = open(&bytes);
    let op_names = op_sheet_names(&wb0);
    assert_eq!(op_names.len(), 3);
    // The Rifter OP sheet's 90_001 row hyperlinks to the Hull OP sheet.
    assert!(
        all_worksheet_xml(&bytes).contains(&format!("location=\"'{}'!A1\"", op_names[1])),
        "parent row links to the child operation sheet"
    );
}

// -- R -- reaction operation: blank/N-A ME/TE, ME Factor 1.
#[tokio::test]
async fn export_reaction_operation_has_na_me_te() {
    let (parent, linked, parent_id, owner_id) = reaction_child_chain(1);
    let (app, _inv) = export_app(parent, owner_id, linked, seeded(vec![]));
    let (status, _h, bytes) = post_export(app, parent_id, overlay(1, hull_section_reacted())).await;
    assert_eq!(status, StatusCode::OK);
    let wb0 = open(&bytes);
    let op_names = op_sheet_names(&wb0);
    assert_eq!(op_names.len(), 2, "Rifter + Hull reaction");
    let mut wb = open(&bytes);

    // Operations row for the reaction op.
    let reaction_op = table_row(&mut wb, "Operations", "Activity", "reaction");
    assert_eq!(cell_text(&reaction_op["ME"]), "n/a");
    assert_eq!(cell_text(&reaction_op["TE"]), "n/a");

    // The reaction OP sheet: header ME/TE = "n/a", ME Factor formula keeps
    // the reaction branch.
    let reaction_sheet = &op_names[1];
    let range = wb.worksheet_range(reaction_sheet).unwrap();
    assert_eq!(cell_text(range.get((6, 1)).unwrap()), "n/a"); // ME (row 7)
    assert_eq!(cell_text(range.get((7, 1)).unwrap()), "n/a"); // TE (row 8)
    assert_eq!(cell_text(range.get((4, 1)).unwrap()), "reaction"); // Activity
    assert!(
        sheet_formulas(&bytes, reaction_sheet).contains("IF($B$5=\"reaction\",1,1-$B$7/100)"),
        "reaction ME Factor -> 1"
    );
}

// -- S / T / U -- Materials Excel totals are SUMIFS over the ledger, never
// the AggregateMaterialLine values.
#[tokio::test]
async fn export_materials_totals_are_sumifs_over_the_ledger() {
    let (parent, linked, parent_id, owner_id) = nested_chain(1);
    let (app, _inv) = export_app(
        parent,
        owner_id,
        linked,
        seeded(vec![(90_001, 1), (34, 400)]),
    );
    let (status, _h, bytes) = post_export(app, parent_id, overlay(1, hull_section_built())).await;
    assert_eq!(status, StatusCode::OK);
    let f = sheet_formulas(&bytes, "Materials");
    assert!(
        f.contains("SUMIFS(Ledger_ExcelRequired,Ledger_TypeId,$A"),
        "S"
    );
    assert!(
        f.contains("SUMIFS(Ledger_ExcelPlannedUse,Ledger_TypeId,$A"),
        "T"
    );
    assert!(
        f.contains("SUMIFS(Ledger_ExcelShortage,Ledger_TypeId,$A"),
        "U"
    );
    // API columns are still raw values.
    let mut wb = open(&bytes);
    let trit = table_row(&mut wb, "Materials", "Type ID", "34");
    assert!(cell_f64(&trit["API Required"]).is_some());
}

// -- V / X / W -- Materials inventory basis from the single balance
// snapshot; Excel Reused Value = Planned Use * Unit Basis; one read.
#[tokio::test]
async fn export_materials_inventory_basis_and_one_read() {
    let (parent, linked, parent_id, owner_id) = nested_chain(1);
    let inv = seeded(vec![(90_001, 1), (34, 400)]).with_unit_basis(34, "5.5");
    let (app, inventory) = export_app(parent, owner_id, linked, inv);
    let (status, _h, bytes) = post_export(app, parent_id, overlay(1, hull_section_built())).await;
    assert_eq!(status, StatusCode::OK);
    assert_eq!(
        inventory.list_balances_call_count(),
        1,
        "W: one list_balances"
    );
    let mut wb = open(&bytes);
    let trit = table_row(&mut wb, "Materials", "Type ID", "34");
    assert_eq!(cell_f64(&trit["Inventory Unit Basis"]), Some(5.5));
    assert_eq!(cell_f64(&trit["Inventory Total Basis"]), Some(2200.0)); // 400 * 5.5
    assert_eq!(cell_f64(&trit["Starting Inventory"]), Some(400.0));
    // Types without a balance entry have blank basis.
    let hull = table_row(&mut wb, "Materials", "Type ID", "35");
    assert!(cell_f64(&hull["Inventory Unit Basis"]).is_none());
    // (X) reused value = planned use * unit basis (cols N * H).
    let materials_f = sheet_formulas(&bytes, "Materials");
    assert!(materials_f.contains("$N2*$H2") || materials_f.contains("$N3*$H3"));
}

// -- Y -- Total Required Volume = Excel Required * Packaged Volume.
#[tokio::test]
async fn export_materials_total_volume_formula() {
    let (parent, linked, parent_id, owner_id) = nested_chain(1);
    let (app, _inv) = export_app(parent, owner_id, linked, seeded(vec![(90_001, 1)]));
    let (status, _h, bytes) = post_export(app, parent_id, overlay(1, hull_section_built())).await;
    assert_eq!(status, StatusCode::OK);
    let f = sheet_formulas(&bytes, "Materials");
    // references Excel Required (col K) and Packaged Volume (col E).
    assert!(f.contains("$K2*$E2") || f.contains("$K3*$E3"), "Y: {f}");
}

// -- Z / AA -- Summary navigation hyperlinks + overall verification.
#[tokio::test]
async fn export_summary_navigation_and_overall_verification() {
    let (parent, linked, parent_id, owner_id) = nested_chain(1);
    let (app, _inv) = export_app(parent, owner_id, linked, seeded(vec![(90_001, 1)]));
    let (status, _h, bytes) = post_export(app, parent_id, overlay(1, hull_section_built())).await;
    assert_eq!(status, StatusCode::OK);
    let wb0 = open(&bytes);
    let op_names = op_sheet_names(&wb0);
    let summary_xml = sheet1_xml(&bytes);
    for name in &op_names {
        assert!(
            summary_xml.contains(&format!("location=\"'{name}'!A1\"")),
            "Z: Summary links to {name}"
        );
    }
    let overall = sheet_formulas(&bytes, "Summary");
    assert!(
        overall.contains("'Allocation Ledger'!") && overall.contains("Operations!"),
        "AA: overall verification spans the ledger and operations: {overall}"
    );
    assert!(overall.contains("\"MISMATCH\""));
}

// -- AB -- Allocation Ledger keeps the independent formula chain + Op #.
#[tokio::test]
async fn export_allocation_ledger_retains_formula_chain() {
    let (parent, linked, parent_id, owner_id) = nested_chain(1);
    let (app, _inv) = export_app(
        parent,
        owner_id,
        linked,
        seeded(vec![(90_001, 1), (34, 400)]),
    );
    let (status, _h, bytes) = post_export(app, parent_id, overlay(1, hull_section_built())).await;
    assert_eq!(status, StatusCode::OK);
    let mut wb = open(&bytes);
    let headers = headers_of(&mut wb, "Allocation Ledger");
    assert!(headers.iter().any(|h| h == "Op #"));
    // The independent recompute is retained but clearly labelled as an
    // audit column, separate from the allocator input "Excel Required".
    assert!(headers.iter().any(|h| h == "Excel Required"));
    assert!(headers.iter().any(|h| h == "Ledger Recomputed Required"));
    assert!(headers.iter().any(|h| h == "Recompute Diff"));
    let f = sheet_formulas(&bytes, "Allocation Ledger");
    for needle in [
        "ROUNDUP(ROUND(", // the recompute column keeps the recipe math
        "SUMIFS(",        // prior planned use
        "MAX(",
        "INDEX(", // child Runs still INDEX/MATCH the child-runs column
        "\"OK\"",
        "\"MISMATCH\"",
        "=\"Full\",0,MIN(",
    ] {
        assert!(f.contains(needle), "ledger keeps {needle}: {f}");
    }
    // Allocator Excel Required (col S) is a back-reference to an OP sheet,
    // never a recompute; the recompute now lives in col T.
    let op_names = op_sheet_names(&open(&bytes));
    assert!(
        formula_cell(&bytes, "Allocation Ledger", "S2").starts_with(&format!("'{}'!", op_names[0])),
        "ledger S2 references the owning OP sheet"
    );
    assert_eq!(
        formula_cell(&bytes, "Allocation Ledger", "T2"),
        "MAX($Q2,ROUNDUP(ROUND($L2*$Q2*$R2*$N2,6),0))",
        "ledger recompute column keeps the independent recipe formula"
    );
}

// -- AC -- Engineering - Requirements retains raw evidence.
#[tokio::test]
async fn export_engineering_requirements_is_raw_evidence() {
    let (parent, linked, parent_id, owner_id) = nested_chain(1);
    let (app, _inv) = export_app(
        parent,
        owner_id,
        linked,
        seeded(vec![(90_001, 1), (34, 400)]),
    );
    let (status, _h, bytes) = post_export(app, parent_id, overlay(1, hull_section_built())).await;
    assert_eq!(status, StatusCode::OK);
    let mut wb = open(&bytes);
    let range = wb.worksheet_range("Engineering - Requirements").unwrap();
    assert!(range.rows().count() > 1, "has rows");
    let headers = headers_of(&mut wb, "Engineering - Requirements");
    for h in ["Op #", "Graph Node ID", "Required Quantity", "Child Runs"] {
        assert!(headers.iter().any(|x| x == h), "AC column {h}");
    }
    // No formulas on this raw sheet.
    assert_eq!(sheet_formulas(&bytes, "Engineering - Requirements"), "");
}

// -- AD / AE -- unsaved overlay reflected; nothing persisted.
#[tokio::test]
async fn export_reflects_overlay_and_never_persists() {
    let (parent, linked, parent_id, owner_id) = nested_chain(2); // persisted runs 2
    let (app, inventory) = export_app(parent, owner_id, linked, seeded(vec![(90_001, 1)]));
    let (status, _h, bytes) =
        post_export(app.clone(), parent_id, overlay(1, hull_section_built())).await;
    assert_eq!(status, StatusCode::OK);
    let mut wb = open(&bytes);
    assert_eq!(
        cell_f64(&ops_value(&mut wb, 0, "Runs (Excel)")),
        Some(1.0),
        "AD: workbook reflects overlay runs, not persisted 2"
    );
    let build = get_build_json(&app, parent_id).await;
    assert_eq!(build["runs"], 2, "AE: persisted runs unchanged");
    assert_eq!(build["revision"], 1, "AE: no write bumped the revision");
    assert_eq!(inventory.list_balances_call_count(), 1);
}

// -- AF -- deterministic structure / order across repeated exports.
#[tokio::test]
async fn export_is_deterministic() {
    let (parent, linked, parent_id, owner_id) = nested_chain(1);
    let (app, _inv) = export_app(
        parent,
        owner_id,
        linked,
        seeded(vec![(90_001, 1), (34, 400)]),
    );
    let summarise = |bytes: &[u8]| {
        let mut wb = open(bytes);
        let names = sheet_names(&wb);
        let ledger_types: Vec<String> = wb
            .worksheet_range("Allocation Ledger")
            .unwrap()
            .rows()
            .skip(1)
            .map(|row| format!("{}|{}", cell_text(&row[0]), cell_text(&row[6])))
            .collect();
        let ops: Vec<String> = wb
            .worksheet_range("Operations")
            .unwrap()
            .rows()
            .skip(1)
            .map(|row| cell_text(&row[0]))
            .collect();
        (names, ledger_types, ops)
    };
    let (_s, _h, first) =
        post_export(app.clone(), parent_id, overlay(1, hull_section_built())).await;
    let (_s, _h, second) =
        post_export(app.clone(), parent_id, overlay(1, hull_section_built())).await;
    assert_eq!(summarise(&first), summarise(&second));
}

// -- content type + filename (kept from the v2 suite) -----------------
#[tokio::test]
async fn export_returns_xlsx_content_type_and_named_attachment() {
    let (parent, linked, parent_id, owner_id) = nested_chain(1);
    let (app, _inv) = export_app(parent, owner_id, linked, seeded(vec![]));
    let (status, headers, bytes) =
        post_export(app, parent_id, overlay(1, hull_section_built())).await;
    assert_eq!(status, StatusCode::OK);
    assert_eq!(
        headers.get(axum::http::header::CONTENT_TYPE).unwrap(),
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    );
    let disposition = headers
        .get(axum::http::header::CONTENT_DISPOSITION)
        .unwrap()
        .to_str()
        .unwrap();
    assert!(disposition.ends_with("-verification.xlsx\""));
    assert_eq!(&bytes[..2], b"PK");
    let _ = open(&bytes);
}

#[tokio::test]
async fn export_filename_is_sanitized_from_the_build_name() {
    let (mut parent, linked, parent_id, owner_id) = nested_chain(1);
    parent.name = "Sabre / Interdictor \"v2\"".to_string();
    let (app, _inv) = export_app(parent, owner_id, linked, seeded(vec![]));
    let (status, headers, _bytes) =
        post_export(app, parent_id, overlay(1, hull_section_built())).await;
    assert_eq!(status, StatusCode::OK);
    assert_eq!(
        headers
            .get(axum::http::header::CONTENT_DISPOSITION)
            .unwrap()
            .to_str()
            .unwrap(),
        "attachment; filename=\"Sabre _ Interdictor _v2-verification.xlsx\""
    );
}

// -- The whole HTTP pipeline (route -> materials_with_planning_cost
// -> VerificationExportModel -> workbook) wires the cost projection
// end-to-end -- cost columns exist, and a priced all-Buy leaf's numbers
// agree between the API evidence and what Excel is given to compute
// from.
#[tokio::test]
async fn export_cost_columns_are_wired_end_to_end_through_the_http_route() {
    let (parent, _ws, owner_id) = rifter_root(1);
    let parent_id = parent.id;
    let (app, _inv) = export_app_priced(parent, owner_id, Vec::new(), seeded(vec![(34, 60)]));
    let (status, _h, bytes) = post_export(app, parent_id, overlay(1, serde_json::json!([]))).await;
    assert_eq!(status, StatusCode::OK);

    let mut wb = open(&bytes);
    let ops_headers = headers_of(&mut wb, "Operations");
    for h in [
        "Excel Material Cost",
        "API Material Cost",
        "Material Cost Delta",
        "Excel Installation",
        "API Installation",
        "Excel Total Cost",
        "Cost Check",
    ] {
        assert!(ops_headers.iter().any(|x| x == h), "Operations column {h}");
    }
    let types_headers = headers_of(&mut wb, "Types");
    assert!(types_headers.iter().any(|x| x == "Adjusted Price (EIV)"));

    let root_sheet = op_sheet_names(&wb)[0].clone();
    let trit = op_table_row(&mut wb, &root_sheet, "34");
    for h in [
        "Inventory Unit Basis",
        "Excel Inventory Cost",
        "API Inventory Cost",
        "Fresh Unit Price",
        "Excel Fresh Cost",
        "API Fresh Cost",
        "Excel Requirement Cost",
        "API Requirement Cost",
        "Cost Status",
    ] {
        assert!(trit.contains_key(h), "OP sheet column {h}");
    }
    // No inventory basis seeded -> the 60 units reused have no known
    // unit cost, so the Buy leaf is cost-incomplete, never zeroed.
    assert!(matches!(trit["Inventory Unit Basis"], Data::Empty));
    // 40 units short @ 5 ISK (fixture_prices-equivalent) = 200.
    assert_eq!(cell_f64(&trit["API Fresh Cost"]), Some(200.0));
}
